fastlane_version '2.59.0'
skip_docs

before_all do  
    ensure_git_branch
    ensure_git_status_clean
    git_pull
end

platform :ios do  
    # iOS Lanes
    desc 'Fetch certificates and provisioning profiles'  
    lane :certificates do
      match(app_identifier: 'tech.azsiaz.LNReader', type: 'development', readonly: true)
      match(app_identifier: 'tech.azsiaz.LNReader', type: 'appstore', readonly: true)
    end

    desc 'Ship to Testflight.'  
    lane :beta do
      certificates
      increment_build_number(xcodeproj: './ios/LNReader.xcodeproj')
      gym(scheme: "LNReader",
        clean: true,
        project: './ios/LNReader.xcodeproj',
        include_bitcode: true)
      clean_build_artifacts
      commit_version_bump(message: 'Bump build', xcodeproj: './ios/LNReader.xcodeproj')
      push_to_git_remote
      pilot
    end
end
